---
- name: Network Agnostic Playbook 
  hosts: aristaswitchessecure
  gather_facts: no
  connection: ansible.builtin.network_cli # mapped in inv as well

  vars:
    ansible_ssh_pass: alta3  # could pass as extra var for security
    dnsserver: "8.8.8.8"
  
  tasks: 
  - name: CONFIGURE DNS 
    ansible.netcommon.cli_config: 
      config: ip name-server {{ dnsserver }}

  - name: CHECK CONFIGURATION 
    ansible.netcommon.cli_command: 
      command: show run | i ip name-server 
    register: results 

  - name: PRINT OUTPUT TO SCREEN 
    ansible.builtin.debug: 
      var: results.stdout

