---              
- name: Deploy mission critical app  
  hosts: planetexpress
  gather_facts: True
  connection: ansible.builtin.ssh

  tasks:
  - name: Cowsay on Debian system (apt)
    ansible.builtin.apt:
      name: cowsay
      state: present
    become: yes
    when: ansible_os_family == "Debian"
    
  - name: Cowsay on RedHat system (yum)
    ansible.builtin.yum:
      name: cowsay
      state: present
    become: yes
    when: ansible_os_family == "RedHat"
    
  - name: Create a README.txt file if it does not exist in every home user directory
    ansible.builtin.lineinfile:
      create: yes
      path: /home/{{ ansible_user }}/README.txt
      line: "Type cowsay 'Moo, my good sir' for a funny display. Use CTRL + C to quit"
    become: yes

